# -*- coding: utf-8 -*-
"""github_downloader

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/106TaBO4OII6KTQlT1HF8sTU8NjM__K3N
"""

import os
import requests


def download_files_from_github(repository_url, folder_path, file_extension='.py'):
    response = requests.get(f"{repository_url}/contents/{folder_path}")
    files = response.json()

    if not os.path.exists(folder_path):
        os.makedirs(folder_path)

    for file in files:
        if file['type'] == 'file' and file['name'].endswith(file_extension):
            file_url = file['download_url']
            file_content = requests.get(file_url).text

            file_path = os.path.join(folder_path, file['name'])
            with open(file_path, 'w') as f:
                f.write(file_content)

            print(f"Downloaded: {file_path}")


if __name__ == "__main__":
    repository_url = "https://api.github.com/repos/Riwaj22/Pytorch"
    folder_path = "Going Modular"
    file_extension = ".py"



    download_files_from_github(repository_url, folder_path, file_extension)